POST http://localhost:5000/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGU1YWU4NDNjNTc3MWEzMTgyYmUzNzkiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU5OTM5Mjc4LCJleHAiOjE3NjAwMjU2Nzh9.EMNgoIgvY2htf_gqKl7WdR5CdA0hjTxJ24G4umKoToU
Content-Type: application/json

{
  "mealName": "new karm meal3",
  "postDate": "2025-10-08T15:56:48.000Z",
  "servings": 5,
  "useBy": "2025-10-09T15:56:48.000Z",
  "pickUpLoc": "123 Main Street",
  "contactPhone": "+1234567890",
  "hold": false,
  "live": true,
  "karm": true,
  "allergens": ["peanuts", "gluten"]
}