POST http://localhost:5000/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNhMjM3MDBlYzE4Mjk0OTZhNGRiOGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU4Mjg1MjM5LCJleHAiOjE3NTgzNzE2Mzl9.Ty8sPxx9PLlTcR-SEPpp8MH9DveLZZth1yFnLHfWyVQ
Content-Type: application/json

{
  "mealName": "Spaghettasdi Baasdsdolognesssss",
  "allergens": ["Gluten", "Dairy"],
  "postDate": "2025-08-15",
  "servings": 3,
  "useBy": "2025-10-20",
  "pickUpLoc": "152 street knoxville",
  "contactPhone": "865 307 3143",
  "hold": false,
  "live": true,
  "karm": false
}
