POST http://localhost:5000/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNhMjM3MDBlYzE4Mjk0OTZhNGRiOGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU4MTY5NTA1LCJleHAiOjE3NTgyNTU5MDV9.DDDo0vio17JNXBoDQUgAaUXTuqhgQ-kqlcKRNjwTWK0
Content-Type: application/json

{
  "mealName": "Spaghetti Bolognes",
  "allergens": ["Gluten", "Dairy"],
  "postDate": "2025-08-15",
  "servings": 3,
  "useBy": "2025-08-20",
  "pickUpLoc": "152 street knoxville",
  "contactPhone": "865 307 3143",
  "hold": false,
  "live": true,
  "karm": false
}
