PATCH http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQ0YmQ3Y2RkMGFlM2E3NTE3MTE0MGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU5MTg4NTc3LCJleHAiOjE3NTkyNzQ5Nzd9.kHK6k7RKuwcr9t_4LLhWQvZB4MiqCpgIUsXekERnojA
Content-Type: application/json

{
  "printName": "forest Wonderland",
  "city": "San Francisco"
}