PATCH http://localhost:5000/api/users/profile/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkXVCJ9.eyJ1c2VySWQiOiI2OGU1NmY1OWI5NzNmNmJiODIxYjYyMmQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU5ODY2NzUwLCJleHAiOjE3NTk5NTMxNTB9.OuOGdUrpwoPMGi2LL75Ok26Hx67XhRzKshkHsS9VaIc

{
  "currentPassword": "Bayleespassword",
  "newPassword": "newPassword"
}