PATCH http://localhost:5000/api/users/profile/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInRcCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGVjMGZiMzgwYWMxZGViZjM5ZjZiYTUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzYwMzAwOTkyLCJleHAiOjE3NjAzODczOTJ9.zACYnqQ4XHhUTkVHiTrxwyBEaZzXuq-AvBi1yxdSlGw

{
  "currentPassword": "esmeraynewpassword",
  "newPassword": "esmeraynewpassword2"
}