const donationsData = [
  {
    id: 1,
    mealName: 'Spaghetti Bolognese',
    allergens: ['Gluten', 'Dairy'],
    postDate: '2025-08-15',
    portionSize: '2 servings',
    useBy: '2025-08-20',
    live: true,
  },
  {
    id: 2,
    mealName: 'Vegan Buddha Bowl',
    allergens: [],
    postDate: '2025-08-14',
    portionSize: '1 large bowl',
    useBy: '2025-08-18',
    live: false,
  },
  {
    id: 3,
    mealName: 'Chicken Curry',
    allergens: ['Peanuts'],
    postDate: '2025-08-16',
    portionSize: '4 servings',
    useBy: '2025-08-21',
    live: false,
  },
  {
    id: 4,
    mealName: 'Quinoa Salad',
    allergens: ['Sesame'],
    postDate: '2025-08-12',
    portionSize: '3 servings',
    useBy: '2025-08-17',
    live: true,
  },
  {
    id: 5,
    mealName: 'Grilled Salmon',
    allergens: ['Fish'],
    postDate: '2025-08-13',
    portionSize: '2 fillets',
    useBy: '2025-08-19',
    live: false,
  },
  {
    id: 6,
    mealName: 'Beef Tacos',
    allergens: ['Gluten'],
    postDate: '2025-08-15',
    portionSize: '6 tacos',
    useBy: '2025-08-20',
    live: true,
  },
  {
    id: 7,
    mealName: 'Misos Soup',
    allergens: ['Soy'],
    postDate: '2025-08-11',
    portionSize: '3 bowls',
    useBy: '2025-08-15',
    live: false,
  },
  {
    id: 8,
    mealName: 'Lentil Stsew',
    allergens: [],
    postDate: '2025-08-10',
    portionSize: '5 servings',
    useBy: '2025-08-14',
    live: false,
  },
  {
    id: 9,
    mealName: 'Shrimp Fried Rice',
    allergens: ['Shellfish', 'Eggs'],
    postDate: '2025-08-09',
    portionSize: '3 portions',
    useBy: '2025-08-13',
    live: false,
  },
  {
    id: 10,
    mealName: 'Vegetable Lasagna',
    allergens: ['Dairy', 'Gluten'],
    postDate: '2025-08-17',
    portionSize: '1 tray',
    useBy: '2025-08-22',
    live: false,
  },
]

export default donationsData
