PATCH http://localhost:5000/api/meals/68e5518d1a73ca819f8c3561/claim
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGU2ZGQ5NmE0YjE2NmIxZTFlYjM5NTYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU5OTYwNDkxLCJleHAiOjE3NjAwNDY4OTF9.hzgsluTtY4RDB3JjHU02qJMH8lM4F4Shsz4iA880zj8
Content-Type: application/json