DELETE http://localhost:5000/api/meals/profile/68d4b4b96a768c5008b2d12c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQ0ODdkNTZhNjhiM2ZjOWFkNmI5YTIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTg3NzAyNTEsImV4cCI6MTc1ODg1NjY1MX0.EbNDo1GSBgBa0aSRZSos6uJ7eN-bVucZW9N_xmktB1s