DELETE http://localhost:5000/api/meals/68cb8dc7e2a2abce08f53ca6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNhMjM3MDBlYzE4Mjk0OTZhNGRiOGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU4Njc3MDI4LCJleHAiOjE3NTg3NjM0Mjh9.1QbL2q1M0LuH4F6BAG2q4WYEsxgddheWHtY4-2FUE2c