DELETE http://localhost:5000/api/meals/profile/68eda38c9c080cb936db4fac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGVkNjVhYjc1OGQ2MWJmOTkwOTk2MGMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzYwNDA0MTY0LCJleHAiOjE3NjA0OTA1NjR9.mMZUx7PW47U_C5ZUo0udCzcOpD-XryonoFfV3Lh_kK0