POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "avatar": "https://yourdomain.com/avatar.jpg",
  "printName": "Lunaaasdsasddasdasdasda",
  "userName": "Esmeray",
  "email": "esmeray@gmail.com",
  "isKarmDonor": true,
  "phone": "+8653073143",
  "country": "Turkey",
  "city": "Izmir",
  "state": "Ege Bolgesi",
  "address": "56/3sk No:19 Daire:13",
  "zipcode": "35350",
  "password": "esmeraypassword1",
  "isAdmin": false
}