PATCH http://localhost:5000/api/meals/profile/68eda3128c6781c6b414a440
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGVkNjVhYjc1OGQ2MWJmOTkwOTk2MGMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzYwNDA2NjI3LCJleHAiOjE3NjA0OTMwMjd9._D9vvhGw2uKweePUjvcO405gZKAy7b6UE1-JkXlmeqM
Content-Type: application/json

{
  "mealName": "New Name",
  "karm": true,
  "servings": 5,
  "allergens": ["peanuts", "soy"]
}