PATCH http://localhost:5000/api/meals/profile/68d4b5f16083e27c1980b1ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGViZDgyYTk0MzdjNGRlZmE4N2E4NDAiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzYwMjg2Nzc1LCJleHAiOjE3NjAzNzMxNzV9.56bhnJkql9b7EhaTXpa9xN6qa0Q9TM3gapEw2kUI3CY
Content-Type: application/json

{
  "mealName": "New Name",
  "useBy": "2025-10-01T18:00:00Z",
  "karm": false,
  "servings": 5,
  "allergens": ["peanuts", "soy"]
}