PATCH http://localhost:5000/api/meals/profile/68d4b5f16083e27c1980b1ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQ0ODdkNTZhNjhiM2ZjOWFkNmI5YTIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTg3NzA2OTIsImV4cCI6MTc1ODg1NzA5Mn0.C4C9-DlFNvcuF_-rjK5Su7pzs09bZFmRqXmhBGC9BiI
Content-Type: application/json

{
  "mealName": "New Name",
  "useBy": "2025-10-01T18:00:00Z",
  "karm": false,
  "servings": 5,
  "allergens": ["peanuts", "soy"]
}