name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Set git user for gh-pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          
      - name: Check GH_TOKEN
        run: '[ -n "$GH_TOKEN" ] && echo GH_TOKEN set || echo GH_TOKEN MISSING'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy