POST http://localhost:5000/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGVkY2IzM2Y2NGY1ZTIzZmFjZWI2OGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzYwNDE0NTM0LCJleHAiOjE3NjA1MDA5MzR9.YxbHo65hwC5k3ampyGR5vkl-El-bxqlrxFYx_tf20y8
Content-Type: application/json

{
  "mealName": "kocaustadorukmeal",
  "allergens": ["Gluten", "Dairy"],
  "postDate": "2025-08-15",
  "servings": 5,
  "useBy": "2025-10-20",
  "pickUpLoc": "152 street knoxville",
  "contactPhone": "865 307 3143",
  "hold": false,
  "live": true,
  "karm": false
}
