POST http://localhost:5000/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQ0ODdkNTZhNjhiM2ZjOWFkNmI5YTIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTg3NTg5MDgsImV4cCI6MTc1ODg0NTMwOH0.9g1Q6IGHZqP56R4kcDLmVPZO60Xazzz_srAyasNp89g
Content-Type: application/json

{
  "mealName": "kedycat`s meal3",
  "allergens": ["Gluten", "Dairy"],
  "postDate": "2025-08-15",
  "servings": 3,
  "useBy": "2025-10-20",
  "pickUpLoc": "152 street knoxville",
  "contactPhone": "865 307 3143",
  "hold": false,
  "live": true,
  "karm": false
}
