POST http://localhost:5000/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGVkNTdkNDZlNzU2YzY1NzgxZjRhMGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzYwMzg1Njk3LCJleHAiOjE3NjA0NzIwOTd9.dzSD-4pDe4bnoacRxIgiWe1cLsNqyNCZZkbZZaSMbVA
Content-Type: application/json

{
  "mealName": "Salad Bowl",
  "allergens": [],
  "postDate": "2025-11-01",
  "servings": "four",
  "useBy": "2025-11-03",
  "pickUpLoc": "123 Market St",
  "contactPhone": "999 888 7777"
}