POST http://localhost:5000/api/meals
Content-Type: application/json

{
  "mealName": "Vegan Curry",
  "allergens": ["Peanuts"],
  "postDate": "2025-09-18",
  "servings": 2,
  "useBy": "2025-09-20",
  "pickUpLoc": "456 Elm St",
  "contactPhone": "222 333 4444"
}